# Spring properties
spring:
  application:
     name: hystrix-dashboard-service  # Service registers under this name
 
server:
  port: 4444   # HTTP (Tomcat) port
 
turbine:
  aggregator:
    clusterConfig: 
  appConfig: 
 
# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/